version: '3.8'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
     - "8088:80"
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
    - mysql

    networks:
    - laravel
    


  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
    - "3306:3306"
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: prueba1
      MYSQL_USER: pablo
      MYSQL_PASSWORD: pablo1234
      MYSQL_ROOT_PASSWORD: pablo9876
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
    - laravel
    tty: true

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
    - ./src:/var/www/html
    ports:
    - "9000:9000"
    networks:
    - laravel

  react:
    image: node:16-alpine
    volumes:
      - ./front:/app:cached
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm start
    